

var funText = new Array ();
funText[0] = "Contains gluten!";
funText[1] = "Likes long walks!";
funText[2] = "Go Celtics!";
funText[3] = "Always safe for work!";
funText[4] = "Not having any nightmares!";
funText[5] = "Eschew obfuscation!";
funText[6] = "Non-alcoholic!";
funText[7] = "May contain allergens!"
funText[8] = "Go Marlins!";
funText[9] = "No artificial preservatives!";
funText[10] = "Est. 1993";
funText[11] = "Interstellar was awesome!";
funText[12] = "Friend of koalas!";
funText[13] = "Thanks for visiting!";
funText[14] = "I have a cat!";
funText[15] = "Tip your waitress!";
funText[16] = "Always low prices. Sometimes.";
funText[17] = "Version 1.2b!";
funText[18] = "Sponsored by my wallet!";
funText[19] = "Submit your own fun quote!";
funText[20] = "Free Willy!";
funText[21] = "I'm professional!";
funText[22] = "Smarter than I was 10 years ago!";
funText[23] = "Whoa!";
funText[24] = "Space Mountain is my favorite!";
funText[25] = "Can leap as high as I can jump!";
funText[26] = "Synergy!";
funText[27] = "50% off today!";
funText[28] = "Please leave a message!";
funText[29] = "Put me in, coach!";
funText[30] = "01101000 01101001!";
funText[31] = "Dancing with the Czars!";
funText[32] = "Heavy duty-free!";
funText[33] = "The joy of discovery!";
funText[34] = "Are you procrastinating?";
funText[35] = "Follow your dreamcatcher!";
funText[36] = "Winter is here!";
funText[37] = "Directed by Steven Spielburg";
funText[38] = "LBDF!";
funText[39] = "#1 Dentist Recommended!";
funText[40] = "Yes And!";
funText[41] = "Founder of the keys I lost yesterday!";
funText[42] = "Shout out to my cat!";

 
var i = Math.floor(43*Math.random());